name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1 # check if we shall use v4
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          overwrite: true

      - name: Cargo build
        run: make build

      - name: Cargo run
        run: make run

      - name: Cargo test
        run: make test

      - name: Run Clippy
        run: make lint
